export const books = [
    {
        name: "Codex Aurora",
        author: "A. I. Generator",
        publishedYear: 2026,
        genre: "Sci-Fi",
        price: 19.99,
        likes: 12,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_1.png"
    },
    {
        name: "Chronicles of Eldoria",
        author: "Fantasio Magus",
        publishedYear: 2025,
        genre: "Fantasy",
        price: 24.50,
        likes: 8,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_2.png"
    },
    {
        name: "The Silent Print",
        author: "Daniel Works",
        publishedYear: 2024,
        genre: "Thriller",
        price: 15.99,
        likes: 5,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_3.png"
    },
    {
        name: "A Love Unfolds",
        author: "Clara Whitmore",
        publishedYear: 2023,
        genre: "Romance",
        price: 12.90,
        likes: 20,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_4.png"
    },
    {
        name: "Chronicles of the Past",
        author: "Henry Morgan",
        publishedYear: 2020,
        genre: "History",
        price: 29.99,
        likes: 15,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_5.png"
    },
    {
        name: "The Traveller's Atlas",
        author: "J. Explorer",
        publishedYear: 2026,
        genre: "Travel",
        price: 35.00,
        likes: 30,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_6.png"
    },
    {
        name: "Financial Mastery",
        author: "Alexander Harrison",
        publishedYear: 2024,
        genre: "Finance",
        price: 49.99,
        likes: 10,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_7.png"
    },
    {
        name: "Fresh Herbs",
        author: "Jane Field",
        publishedYear: 2022,
        genre: "Cooking",
        price: 18.50,
        likes: 11,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_8.png"
    },
    {
        name: "Meditations",
        author: "Marcus Aurelius",
        publishedYear: 180,
        genre: "Philosophy",
        price: 9.99,
        likes: 55,
        liked: false,
        comments: [],
        isFavorite: false,
        image: "titel_9.png"
    }
];